/**
 * 字典key 编码 常量
 *
 * 该常量来自于 字典管理中的数据，写在该文件目的是为了统一引用，将来好修改
 *
 * @Author:    1024创新实验室-主任：卓大
 * @Date:      2024-09-03 22:09:10
 * @Wechat:    zhuda1024
 * @Email:     lab1024@163.com
 * @Copyright  1024创新实验室 （ https://1024lab.net ），Since 2012
 */

export const DICT_SPLIT = ',';

export const DICT_CODE_ENUM = {
  TEMPLATE_TYPE: 'TEMPLATE_TYPE',
  GOODS_PLACE: 'GOODS_PLACE',
  DATABASE_TYPE: 'DATABASE_TYPE',
  LANGUAGE_TYPE: 'LANGUAGE_TYPE',
  TEMPLATE_COLUMN_MAPPING: 'TEMPLATE_COLUMN_MAPPING',
  DATABASE_COLUMN_TYPE: 'DATABASE_COLUMN_TYPE',
  FRONT_COLUMN_TYPE: 'FRONT_COLUMN_TYPE',
  JAVA_FIELD_TYPE: 'JAVA_FIELD_TYPE',
  FRONT_FIELD_TYPE: 'FRONT_FIELD_TYPE',
  CODE_TEMPLATE_TYPE: 'CODE_TEMPLATE_TYPE',
  FILE_NAME: 'FILE_NAME',
  FILE_TYPE: 'FILE_TYPE',
  WHERE_TYPE: 'WHERE_TYPE',
  FRONT_COMPONENT: 'FRONT_COMPONENT',
  ORDER_TYPE: 'ORDER_TYPE',
};

export default {
  DICT_CODE_ENUM,
};
